[packages]
brews = [
  # NORMAL BREWS
  "awscli",
  "bash",
  "coreutils",
  "deno",
  "ffmpeg",
  "flyctl",
  "git",
  "git-delta",
  "git-extras",
  "git-lfs",
  "gnupg",
  "handbrake",
  "htop",
  "jq",
  "less",
  "lua",
  "ncdu",
  "ncurses",
  "pintentry-mac",
  "pyenv",
  "readline",
  "rename",
  "safe-rm",
  "shellcheck",
  "thefuck",
  "tmux",
  "tree",
  "wget",
  "wireguard-tools",
  "youtube-dl",
  "zsh",

  # CASK BREWS
  "alfred",
  "bartender",
  "brave-browser",
  "docker",
  "figma",
  "firefox",
  "fontgoggles",
  "glyphs",
  "google-chrome",
  "imageoptim",
  "insomnia",
  "iterm2",
  "java",
  "jetbrains-toolbox",
  "kap",
  "logitune",
  "loopback",
  "notion",
  "private-internet-access",
  "qlcolorcode",
  "qlimagesize",
  "qlmarkdown",
  "qlstephen",
  "qlvideo",
  "quicklook-json",
  "quicklookase",
  "rectangle",
  "rive",
  "rocket",
  "slack",
  "spotify",
  "sublime-text",
  "visual-studio-code",
  "vlc",
  "webpquicklook"
]
